//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.431.
// 
#pragma warning disable 1591

namespace SIGE.Facade_Interface_EasyWin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Facade_Info_EasyWin_for_SIGESoap", Namespace="http://tempuri.org/")]
    public partial class Facade_Info_EasyWin_for_SIGE : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PresupuestoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Presupuesto_SearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Obtener_Presupuestos_UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_NamePlanningOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_OtenerFechasPlanningOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ObtenerClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ObtenerPersonalcalleOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ObtenerSupervisoresOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Facade_Info_EasyWin_for_SIGE() {
            this.Url = global::SIGE.Properties.Settings.Default.SIGE_Facade_Interface_EasyWin_Facade_Info_EasyWin_for_SIGE;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PresupuestoCompletedEventHandler PresupuestoCompleted;
        
        /// <remarks/>
        public event Presupuesto_SearchCompletedEventHandler Presupuesto_SearchCompleted;
        
        /// <remarks/>
        public event Get_Obtener_Presupuestos_UpdateCompletedEventHandler Get_Obtener_Presupuestos_UpdateCompleted;
        
        /// <remarks/>
        public event Get_NamePlanningCompletedEventHandler Get_NamePlanningCompleted;
        
        /// <remarks/>
        public event Get_OtenerFechasPlanningCompletedEventHandler Get_OtenerFechasPlanningCompleted;
        
        /// <remarks/>
        public event Get_ObtenerClientesCompletedEventHandler Get_ObtenerClientesCompleted;
        
        /// <remarks/>
        public event Get_ObtenerPersonalcalleCompletedEventHandler Get_ObtenerPersonalcalleCompleted;
        
        /// <remarks/>
        public event Get_ObtenerSupervisoresCompletedEventHandler Get_ObtenerSupervisoresCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Presupuesto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Presupuesto(string scountry, int iCompany_id) {
            object[] results = this.Invoke("Presupuesto", new object[] {
                        scountry,
                        iCompany_id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PresupuestoAsync(string scountry, int iCompany_id) {
            this.PresupuestoAsync(scountry, iCompany_id, null);
        }
        
        /// <remarks/>
        public void PresupuestoAsync(string scountry, int iCompany_id, object userState) {
            if ((this.PresupuestoOperationCompleted == null)) {
                this.PresupuestoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPresupuestoOperationCompleted);
            }
            this.InvokeAsync("Presupuesto", new object[] {
                        scountry,
                        iCompany_id}, this.PresupuestoOperationCompleted, userState);
        }
        
        private void OnPresupuestoOperationCompleted(object arg) {
            if ((this.PresupuestoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PresupuestoCompleted(this, new PresupuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Presupuesto_Search", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Presupuesto_Search(int iCompany_id) {
            object[] results = this.Invoke("Presupuesto_Search", new object[] {
                        iCompany_id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Presupuesto_SearchAsync(int iCompany_id) {
            this.Presupuesto_SearchAsync(iCompany_id, null);
        }
        
        /// <remarks/>
        public void Presupuesto_SearchAsync(int iCompany_id, object userState) {
            if ((this.Presupuesto_SearchOperationCompleted == null)) {
                this.Presupuesto_SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPresupuesto_SearchOperationCompleted);
            }
            this.InvokeAsync("Presupuesto_Search", new object[] {
                        iCompany_id}, this.Presupuesto_SearchOperationCompleted, userState);
        }
        
        private void OnPresupuesto_SearchOperationCompleted(object arg) {
            if ((this.Presupuesto_SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Presupuesto_SearchCompleted(this, new Presupuesto_SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Obtener_Presupuestos_Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Get_Obtener_Presupuestos_Update(string snamepresu) {
            object[] results = this.Invoke("Get_Obtener_Presupuestos_Update", new object[] {
                        snamepresu});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Obtener_Presupuestos_UpdateAsync(string snamepresu) {
            this.Get_Obtener_Presupuestos_UpdateAsync(snamepresu, null);
        }
        
        /// <remarks/>
        public void Get_Obtener_Presupuestos_UpdateAsync(string snamepresu, object userState) {
            if ((this.Get_Obtener_Presupuestos_UpdateOperationCompleted == null)) {
                this.Get_Obtener_Presupuestos_UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Obtener_Presupuestos_UpdateOperationCompleted);
            }
            this.InvokeAsync("Get_Obtener_Presupuestos_Update", new object[] {
                        snamepresu}, this.Get_Obtener_Presupuestos_UpdateOperationCompleted, userState);
        }
        
        private void OnGet_Obtener_Presupuestos_UpdateOperationCompleted(object arg) {
            if ((this.Get_Obtener_Presupuestos_UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Obtener_Presupuestos_UpdateCompleted(this, new Get_Obtener_Presupuestos_UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_NamePlanning", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Get_NamePlanning(string snumbrerpresupuesto) {
            object[] results = this.Invoke("Get_NamePlanning", new object[] {
                        snumbrerpresupuesto});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Get_NamePlanningAsync(string snumbrerpresupuesto) {
            this.Get_NamePlanningAsync(snumbrerpresupuesto, null);
        }
        
        /// <remarks/>
        public void Get_NamePlanningAsync(string snumbrerpresupuesto, object userState) {
            if ((this.Get_NamePlanningOperationCompleted == null)) {
                this.Get_NamePlanningOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_NamePlanningOperationCompleted);
            }
            this.InvokeAsync("Get_NamePlanning", new object[] {
                        snumbrerpresupuesto}, this.Get_NamePlanningOperationCompleted, userState);
        }
        
        private void OnGet_NamePlanningOperationCompleted(object arg) {
            if ((this.Get_NamePlanningCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_NamePlanningCompleted(this, new Get_NamePlanningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_OtenerFechasPlanning", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Get_OtenerFechasPlanning(string snumberpresupuesto, int ivalor) {
            object[] results = this.Invoke("Get_OtenerFechasPlanning", new object[] {
                        snumberpresupuesto,
                        ivalor});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Get_OtenerFechasPlanningAsync(string snumberpresupuesto, int ivalor) {
            this.Get_OtenerFechasPlanningAsync(snumberpresupuesto, ivalor, null);
        }
        
        /// <remarks/>
        public void Get_OtenerFechasPlanningAsync(string snumberpresupuesto, int ivalor, object userState) {
            if ((this.Get_OtenerFechasPlanningOperationCompleted == null)) {
                this.Get_OtenerFechasPlanningOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_OtenerFechasPlanningOperationCompleted);
            }
            this.InvokeAsync("Get_OtenerFechasPlanning", new object[] {
                        snumberpresupuesto,
                        ivalor}, this.Get_OtenerFechasPlanningOperationCompleted, userState);
        }
        
        private void OnGet_OtenerFechasPlanningOperationCompleted(object arg) {
            if ((this.Get_OtenerFechasPlanningCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_OtenerFechasPlanningCompleted(this, new Get_OtenerFechasPlanningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_ObtenerClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Get_ObtenerClientes(string snumberpresupuesto, int ivalor) {
            object[] results = this.Invoke("Get_ObtenerClientes", new object[] {
                        snumberpresupuesto,
                        ivalor});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Get_ObtenerClientesAsync(string snumberpresupuesto, int ivalor) {
            this.Get_ObtenerClientesAsync(snumberpresupuesto, ivalor, null);
        }
        
        /// <remarks/>
        public void Get_ObtenerClientesAsync(string snumberpresupuesto, int ivalor, object userState) {
            if ((this.Get_ObtenerClientesOperationCompleted == null)) {
                this.Get_ObtenerClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ObtenerClientesOperationCompleted);
            }
            this.InvokeAsync("Get_ObtenerClientes", new object[] {
                        snumberpresupuesto,
                        ivalor}, this.Get_ObtenerClientesOperationCompleted, userState);
        }
        
        private void OnGet_ObtenerClientesOperationCompleted(object arg) {
            if ((this.Get_ObtenerClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ObtenerClientesCompleted(this, new Get_ObtenerClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_ObtenerPersonalcalle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Get_ObtenerPersonalcalle(string snumberpresupuesto, int ivalor) {
            object[] results = this.Invoke("Get_ObtenerPersonalcalle", new object[] {
                        snumberpresupuesto,
                        ivalor});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Get_ObtenerPersonalcalleAsync(string snumberpresupuesto, int ivalor) {
            this.Get_ObtenerPersonalcalleAsync(snumberpresupuesto, ivalor, null);
        }
        
        /// <remarks/>
        public void Get_ObtenerPersonalcalleAsync(string snumberpresupuesto, int ivalor, object userState) {
            if ((this.Get_ObtenerPersonalcalleOperationCompleted == null)) {
                this.Get_ObtenerPersonalcalleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ObtenerPersonalcalleOperationCompleted);
            }
            this.InvokeAsync("Get_ObtenerPersonalcalle", new object[] {
                        snumberpresupuesto,
                        ivalor}, this.Get_ObtenerPersonalcalleOperationCompleted, userState);
        }
        
        private void OnGet_ObtenerPersonalcalleOperationCompleted(object arg) {
            if ((this.Get_ObtenerPersonalcalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ObtenerPersonalcalleCompleted(this, new Get_ObtenerPersonalcalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_ObtenerSupervisores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Get_ObtenerSupervisores(string snumberpresupuesto, int ivalor) {
            object[] results = this.Invoke("Get_ObtenerSupervisores", new object[] {
                        snumberpresupuesto,
                        ivalor});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Get_ObtenerSupervisoresAsync(string snumberpresupuesto, int ivalor) {
            this.Get_ObtenerSupervisoresAsync(snumberpresupuesto, ivalor, null);
        }
        
        /// <remarks/>
        public void Get_ObtenerSupervisoresAsync(string snumberpresupuesto, int ivalor, object userState) {
            if ((this.Get_ObtenerSupervisoresOperationCompleted == null)) {
                this.Get_ObtenerSupervisoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ObtenerSupervisoresOperationCompleted);
            }
            this.InvokeAsync("Get_ObtenerSupervisores", new object[] {
                        snumberpresupuesto,
                        ivalor}, this.Get_ObtenerSupervisoresOperationCompleted, userState);
        }
        
        private void OnGet_ObtenerSupervisoresOperationCompleted(object arg) {
            if ((this.Get_ObtenerSupervisoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ObtenerSupervisoresCompleted(this, new Get_ObtenerSupervisoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PresupuestoCompletedEventHandler(object sender, PresupuestoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PresupuestoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PresupuestoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Presupuesto_SearchCompletedEventHandler(object sender, Presupuesto_SearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Presupuesto_SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Presupuesto_SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Get_Obtener_Presupuestos_UpdateCompletedEventHandler(object sender, Get_Obtener_Presupuestos_UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Obtener_Presupuestos_UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Obtener_Presupuestos_UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Get_NamePlanningCompletedEventHandler(object sender, Get_NamePlanningCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_NamePlanningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_NamePlanningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Get_OtenerFechasPlanningCompletedEventHandler(object sender, Get_OtenerFechasPlanningCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_OtenerFechasPlanningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_OtenerFechasPlanningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Get_ObtenerClientesCompletedEventHandler(object sender, Get_ObtenerClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ObtenerClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ObtenerClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Get_ObtenerPersonalcalleCompletedEventHandler(object sender, Get_ObtenerPersonalcalleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ObtenerPersonalcalleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ObtenerPersonalcalleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Get_ObtenerSupervisoresCompletedEventHandler(object sender, Get_ObtenerSupervisoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ObtenerSupervisoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ObtenerSupervisoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591